version: "2"

services:
  web:
    image: nginx
    ports:
      - 80
      - 443
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - appdata
    links:
      - phpfpm
    environment:
      - VIRTUAL_HOST=dev.broxtowelabour.com
      - VIRTUAL_PORT=80

  phpfpm:
    image: php:7.0-fpm
    volumes_from:
      - appdata
    ports:
      - 9000

  cli:
    image: tatemz/wp-cli
    volumes_from:
      - appdata
    links:
      - db
      - phpfpm
    entrypoint:
      - wp
    command: "--info"

  db:
    image: mysql
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=broxtowe_labour
      - MYSQL_USER=broxtowe_labour
      - MYSQL_PASSWORD=broxtowe_labour

  appdata:
    image: tianon/true
    volumes:
      - ../:/var/www/html